### ISSUE TITLE
Making SAM 2 run 2x faster

### ISSUE THREAD

**Issue by mvoodarla** [autodistill/autodistill-grounded-sam-2#7]
I was pretty amazed with SAM 2 when it came out given all the work I do with video. My company works a ton with it and we decided to take a crack at optimizing it, and we made it run 2x faster than the original pipeline!

Unlike LLMs, video models are notorious for incredibly inefficient file reading, storage, and writing which makes them much slower than they need to be.

We wrote a bit about our work here and thought we'd share with the community:
https://www.sievedata.com/blog/meta-segment-anything-2-sam2-introduction

**Comment by yeldarby** [comment]
Hey, great job! Are you contributing your improvements back to the open source community?

**Comment by mvoodarla** [comment]
Some of the improvements made unfortunately are more compute / system dependent than codebase which is why right now we're just offering API access to the improvements. We'll definitely consider writing a more technical post detailing the optimizations though so people can take whatever they can & self-host.

Separately, we'll look into ways we might be able to help improve SAM2 grounding with approaches past Florence-2 that we will try to contribute back. Curious what you've found the limitations with Florence-2 to be in this aspect?
